import { Facility, Task } from "../App"

export const tasks: Array<Task> = [
  {
    id: 1,
    title: "PP1A",
    description: "Description 1",
    bgcolor: "#D5009A",
    duration: 4,
    dropped: false,
  },
  {
    id: 2,
    title: "PP1B",
    description: "Description 2",
    bgcolor: "#D5009A",
    duration: 10,
    dropped: false,
  },
  {
    id: 3,
    title: "PP2A",
    description: "Description 3",
    bgcolor: "#00A2D5",
    duration: 12,
    dropped: false,
  },
  {
    id: 4,
    title: "PP2B",
    description: "Description 4",
    bgcolor: "#00A2D5",
    duration: 7,
    dropped: false,
  },
  {
    id: 5,
    title: "PP3A",
    description: "Description 1",
    bgcolor: "#04D500",
    duration: 18,
    dropped: false,
  },
  {
    id: 6,
    title: "PP3B",
    description: "Description 2",
    bgcolor: "#04D500",
    duration: 11,
    dropped: false,
  },
  {
    id: 7,
    title: "PP3C",
    description: "Description 3",
    bgcolor: "#04D500",
    duration: 7,
    dropped: false,
  },
  {
    id: 8,
    title: "PP4A",
    description: "Description 4",
    bgcolor: "#9100D5",
    duration: 46,
    dropped: false,
  },
  {
    id: 9,
    title: "PP5A",
    description: "Description 4",
    bgcolor: "#D5CD00",
    duration: 25,
    dropped: false,
  },
  {
    id: 10,
    title: "PP5B",
    description: "Description 4",
    bgcolor: "#D5CD00",
    duration: 9,
    dropped: false,
  },
  {
    id: 11,
    title: "PP5C",
    description: "Description 4",
    bgcolor: "#D5CD00",
    duration: 4,
    dropped: false,
  },
]

export const stands: Array<Facility> = [
  {
    id: 1,
    title: "BOP GDANSK SPAW 1",
    description: "Description 1",
    bgcolor: "#F2FFA4",
  },
  {
    id: 2,
    title: "BOP GDANSK PREFAB 1",
    description: "Description 2",
    bgcolor: "#FF9E9E",
  },
  {
    id: 3,
    title: "BOP GDANSK MAL 1",
    description: "Description 4",
    bgcolor: "#C598FF",
  },
  {
    id: 4,
    title: "BOP GDANSK MAL 2",
    description: "Description 4",
    bgcolor: "#C598FF",
  },
  {
    id: 5,
    title: "BOP GDYNIA SPAW 1",
    description: "Description 3",
    bgcolor: "#B3FFCD",
  },
  {
    id: 6,
    title: "BOP GDYNIA SPAW 2",
    description: "Description 4",
    bgcolor: "#B3FFCD",
  },
  {
    id: 7,
    title: "BOP GDYNIA PREFAB 1",
    description: "Description 4",
    bgcolor: "#9FD1FF",
  },
]
